# Generated by Django 3.1.7 on 2021-05-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clinic', models.CharField(max_length=50)),
                ('consultation_fee', models.IntegerField(default=500)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('joining_date', models.DateTimeField(verbose_name='date published')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.doctors')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
