# Generated by Django 3.1.7 on 2021-05-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20210505_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneme', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('illustration_video', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('audio_file', models.CharField(max_length=500)),
                ('illustration_video', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.wordsattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.DateTimeField(verbose_name='your slot')),
                ('feedback', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.user')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.doctor')),
            ],
        ),
    ]
