# Generated by Django 3.1.7 on 2021-05-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_appointment_word_wordsattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.wordsattribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_audio', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.user')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.word')),
            ],
        ),
    ]
