# Generated by Django 3.1.7 on 2021-05-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_remove_user_use_rname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='shalini', max_length=50),
            preserve_default=False,
        ),
    ]
